import type {
  User,
  Service,
  Project,
  Share,
  FinancialProduct,
  Transaction,
  Level,
  PromoCode,
  Department,
  SiteContent,
  InvestorRequest,
  Task,
  TaskSubmission,
  ChatMessage,
  ContactLinks,
  PartnerRequest,
} from './types'

export const seedUsers: User[] = [
  {
    id: 'u1',
    name: 'أحمد المصري',
    phone: '+201001234567',
    nationalId: '29001011234567',
    code: 'INV-1001',
    password: '123456',
    role: 'investor',
    rank: 'مستثمر ذهبي',
    dept: null,
    points: 1200,
    shares: 35,
    wallet: 48500,
    status: 'approved',
    securityQuestion: 'ما اسم مدينتك المفضلة؟',
    securityAnswer: 'القاهرة',
    portfolioUrl: 'https://example.com/ahmed-portfolio',
    portfolioFiles: ['portfolio.pdf', 'intro-video.mp4', 'voice-note.mp3'],
    createdAt: '2024-01-15',
  },
  {
    id: 'u2',
    name: 'سارة عبد الله',
    phone: '+201112223334',
    nationalId: '29505052345678',
    code: 'PRT-2002',
    password: '123456',
    role: 'partner',
    rank: 'شريك فضي',
    dept: 'التسويق',
    points: 2300,
    shares: 12,
    wallet: 15200,
    status: 'approved',
    securityQuestion: 'ما اسم حيوانك الأليف الأول؟',
    securityAnswer: 'لولو',
    portfolioUrl: 'https://example.com/sara-work',
    portfolioFiles: ['designs.pdf', 'reel.mp4'],
    createdAt: '2024-02-20',
  },
]

export const seedServices: Service[] = [
  {
    id: 's1',
    titleAr: 'الاستثمار الذكي',
    titleEn: 'Smart Investing',
    descAr: 'استثمر أموالك في محافظ مدروسة بعوائد مستقرة وإدارة احترافية للمخاطر.',
    descEn: 'Invest in curated portfolios with stable returns and professional risk management.',
    icon: 'TrendingUp',
    imageUrl: '/smart-investing-finance-dashboard.png',
    videoUrl: null,
    columns: [
      { labelAr: 'الحد الأدنى', labelEn: 'Minimum', valueAr: '5,000 ج.م', valueEn: '5,000 EGP' },
      { labelAr: 'العائد المتوقع', labelEn: 'Expected Return', valueAr: '18%', valueEn: '18%' },
    ],
    order: 1,
    active: true,
  },
  {
    id: 's2',
    titleAr: 'الشراكة التجارية',
    titleEn: 'Business Partnership',
    descAr: 'انضم كشريك فعّال وشارك في إدارة المشاريع واكسب نقاط الترقية والمكافآت.',
    descEn: 'Join as an active partner, manage projects, and earn promotion points and rewards.',
    icon: 'Handshake',
    imageUrl: '/business-partnership-handshake.png',
    videoUrl: null,
    columns: [
      { labelAr: 'الأقسام', labelEn: 'Departments', valueAr: '8 أقسام', valueEn: '8 Depts' },
      { labelAr: 'المكافآت', labelEn: 'Rewards', valueAr: 'نقاط + حصص', valueEn: 'Points + Shares' },
    ],
    order: 2,
    active: true,
  },
  {
    id: 's3',
    titleAr: 'إدارة المحافظ',
    titleEn: 'Portfolio Management',
    descAr: 'فريق متخصص يدير محفظتك ويوزع الأرباح بشفافية كاملة وتقارير دورية.',
    descEn: 'A dedicated team manages your portfolio and distributes profits transparently.',
    icon: 'PieChart',
    imageUrl: '/portfolio-management-charts-analytics.png',
    videoUrl: null,
    columns: [
      { labelAr: 'التقارير', labelEn: 'Reports', valueAr: 'شهرية', valueEn: 'Monthly' },
      { labelAr: 'الشفافية', labelEn: 'Transparency', valueAr: '100%', valueEn: '100%' },
    ],
    order: 3,
    active: true,
  },
]

export const seedProjects: Project[] = [
  {
    id: 'p1',
    titleAr: 'مجمع عرباوي التجاري',
    titleEn: 'Arabaawy Commercial Hub',
    descAr: 'مشروع تجاري ضخم في قلب العاصمة بعوائد استثمارية مرتفعة على المدى الطويل.',
    descEn: 'A large commercial project in the heart of the capital with high long-term returns.',
    progress: 72,
    investorsCount: 340,
    tag: 'عقاري',
    imageUrl: '/modern-commercial-building-complex.png',
    active: true,
  },
  {
    id: 'p2',
    titleAr: 'منصة عرباوي التقنية',
    titleEn: 'Arabaawy Tech Platform',
    descAr: 'منصة رقمية ناشئة تربط المستثمرين بالمشاريع التقنية الواعدة في المنطقة.',
    descEn: 'A digital platform connecting investors with promising tech ventures in the region.',
    progress: 45,
    investorsCount: 180,
    tag: 'تقني',
    imageUrl: '/tech-startup-office-team.png',
    active: true,
  },
  {
    id: 'p3',
    titleAr: 'مزارع عرباوي الزراعية',
    titleEn: 'Arabaawy Agri Farms',
    descAr: 'استثمار زراعي مستدام في أراضٍ خصبة مع تقنيات ري حديثة وعوائد موسمية.',
    descEn: 'Sustainable agricultural investment with modern irrigation and seasonal returns.',
    progress: 88,
    investorsCount: 510,
    tag: 'زراعي',
    imageUrl: '/green-agriculture-farm-fields.png',
    active: true,
  },
]

export const seedShares: Share[] = [
  {
    id: 'sh1',
    name: 'حصة عرباوي التجارية',
    price: 1500,
    total: 1000,
    available: 280,
    buyEnabled: true,
    sellEnabled: true,
    published: true,
  },
  {
    id: 'sh2',
    name: 'حصة المنصة التقنية',
    price: 2200,
    total: 500,
    available: 120,
    buyEnabled: true,
    sellEnabled: false,
    published: true,
  },
  {
    id: 'sh3',
    name: 'حصة المزارع',
    price: 900,
    total: 2000,
    available: 640,
    buyEnabled: true,
    sellEnabled: true,
    published: true,
  },
]

export const seedProducts: FinancialProduct[] = [
  {
    id: 'fp1',
    nameAr: 'صندوق النمو الذهبي',
    nameEn: 'Golden Growth Fund',
    descAr: 'صندوق استثماري متوازن بعائد سنوي مرتفع وإدارة محترفة للمخاطر.',
    descEn: 'A balanced fund with high annual returns and professional risk management.',
    returnRate: 22,
    minInvest: 10000,
    status: 'active',
    active: true,
  },
  {
    id: 'fp2',
    nameAr: 'وديعة المارد المجمّدة',
    nameEn: 'Marid Frozen Deposit',
    descAr: 'وديعة طويلة الأجل مرتبطة بمشروع المجمع التجاري، مجمدة حتى الانتهاء.',
    descEn: 'A long-term deposit tied to the commercial hub project, frozen until completion.',
    returnRate: 30,
    minInvest: 25000,
    status: 'frozen',
    active: true,
  },
  {
    id: 'fp3',
    nameAr: 'محفظة المزارع الموسمية',
    nameEn: 'Seasonal Farms Portfolio',
    descAr: 'محفظة موسمية مكتملة الدورة، تم توزيع أرباحها بالكامل.',
    descEn: 'A completed seasonal portfolio with fully distributed profits.',
    returnRate: 15,
    minInvest: 5000,
    status: 'completed',
    active: true,
  },
]

export const seedTransactions: Transaction[] = [
  { id: 't1', userId: 'u1', type: 'deposit', amount: 50000, date: '2024-06-01', notes: 'إيداع أولي', status: 'approved' },
  { id: 't2', userId: 'u1', type: 'buy', amount: 15000, date: '2024-06-05', notes: 'شراء 10 حصص تجارية', status: 'approved' },
  { id: 't3', userId: 'u1', type: 'distribution', amount: 4200, date: '2024-07-01', notes: 'توزيع أرباح الربع الثاني', status: 'approved' },
  { id: 't4', userId: 'u1', type: 'sell', amount: 3000, date: '2024-07-15', notes: 'بيع حصتين', status: 'approved' },
  { id: 't5', userId: 'u1', type: 'withdraw', amount: 8000, date: '2024-08-02', notes: 'سحب جزئي', status: 'pending' },
  { id: 't6', userId: 'u1', type: 'deposit', amount: 12000, date: '2024-09-10', notes: 'إيداع إضافي', status: 'approved' },
  { id: 't7', userId: 'u2', type: 'deposit', amount: 15000, date: '2024-06-20', notes: 'إيداع شريك', status: 'approved' },
  { id: 't8', userId: 'u2', type: 'distribution', amount: 1800, date: '2024-08-01', notes: 'مكافأة مهام', status: 'approved' },
]

export const seedLevels: Level[] = [
  { id: 'l1', nameAr: 'برونزي', nameEn: 'Bronze', minPoints: 0, requirementsAr: 'تسجيل حساب نشط', requirementsEn: 'Active account', color: '#cd7f32', icon: 'Medal' },
  { id: 'l2', nameAr: 'فضي', nameEn: 'Silver', minPoints: 1000, requirementsAr: '1000 نقطة + استثمار واحد', requirementsEn: '1000 pts + 1 investment', color: '#c0c0c0', icon: 'Award' },
  { id: 'l3', nameAr: 'ذهبي', nameEn: 'Gold', minPoints: 2500, requirementsAr: '2500 نقطة + 3 استثمارات', requirementsEn: '2500 pts + 3 investments', color: '#ffd700', icon: 'Trophy' },
  { id: 'l4', nameAr: 'ماسي', nameEn: 'Diamond', minPoints: 5000, requirementsAr: '5000 نقطة + شراكة فعالة', requirementsEn: '5000 pts + active partnership', color: '#00c6ff', icon: 'Gem' },
]

export const seedPromoCodes: PromoCode[] = [
  { id: 'pc1', code: 'PROMO-WELCOME', discount: 10, uses: 24, maxUses: 100, active: true },
  { id: 'pc2', code: 'PROMO-VIP25', discount: 25, uses: 8, maxUses: 50, active: true },
]

export const seedDepartments: Department[] = [
  { id: 'd1', code: 'MKT', name: 'التسويق', capacity: 20, currentCount: 14, active: true },
  { id: 'd2', code: 'SAL', name: 'المبيعات', capacity: 15, currentCount: 15, active: false },
  { id: 'd3', code: 'TEC', name: 'التقنية', capacity: 12, currentCount: 7, active: true },
  { id: 'd4', code: 'FIN', name: 'المالية', capacity: 10, currentCount: 5, active: true },
  { id: 'd5', code: 'OPS', name: 'العمليات', capacity: 18, currentCount: 9, active: true },
  { id: 'd6', code: 'SUP', name: 'الدعم', capacity: 14, currentCount: 6, active: true },
  { id: 'd7', code: 'HR', name: 'الموارد البشرية', capacity: 8, currentCount: 4, active: true },
  { id: 'd8', code: 'LEG', name: 'الشؤون القانونية', capacity: 6, currentCount: 3, active: true },
]

export const seedContent: SiteContent = {
  welcomeAr: 'مرحباً بك في عرباوي، حيث تتحول أحلامك الاستثمارية إلى واقع.',
  welcomeEn: 'Welcome to Arabaawy, where your investment dreams become reality.',
  heroTitleAr: 'استثمر بذكاء، واشترك بقوة',
  heroTitleEn: 'Invest Smart, Partner Strong',
  heroSubAr: 'منصة عرباوي تجمع بين المستثمرين والشركاء في مشاريع ناجحة بعوائد حقيقية وشفافية كاملة.',
  heroSubEn: 'Arabaawy connects investors and partners in successful projects with real returns and full transparency.',
  clientPortalAr: 'بوابة العملاء',
  clientPortalEn: 'Client Portal',
}

export const seedRequests: InvestorRequest[] = [
  {
    id: 'r1',
    name: 'محمد خالد',
    phone: '+201234567890',
    nationalId: '29208083456789',
    portfolioUrl: 'https://example.com/mohamed',
    portfolioFiles: ['cv.pdf', 'intro.mp4'],
    securityQuestion: 'ما اسم مدرستك الابتدائية؟',
    status: 'pending',
    code: null,
    createdAt: '2024-09-15',
  },
  {
    id: 'r2',
    name: 'ليلى حسن',
    phone: '+201555666777',
    nationalId: '29711114567890',
    portfolioUrl: 'https://example.com/laila',
    portfolioFiles: ['portfolio.pdf'],
    securityQuestion: 'ما طعامك المفضل؟',
    status: 'pending',
    code: null,
    createdAt: '2024-09-18',
  },
]

export const seedTasks: Task[] = [
  {
    id: 'tk1',
    titleAr: 'حملة تسويقية على إنستغرام',
    titleEn: 'Instagram Marketing Campaign',
    descAr: 'إنشاء وإدارة حملة إعلانية لمدة أسبوع للترويج لمشروع المجمع التجاري.',
    descEn: 'Create and run a one-week ad campaign promoting the commercial hub project.',
    rewardPoints: 300,
    deadline: '2024-10-15',
    assignedTo: 'all',
    active: true,
  },
  {
    id: 'tk2',
    titleAr: 'تصميم عرض تقديمي للمستثمرين',
    titleEn: 'Investor Pitch Deck Design',
    descAr: 'تصميم عرض احترافي من 12 شريحة لعرضه على المستثمرين الجدد.',
    descEn: 'Design a professional 12-slide deck to present to new investors.',
    rewardPoints: 450,
    deadline: '2024-10-20',
    assignedTo: 'all',
    active: true,
  },
  {
    id: 'tk3',
    titleAr: 'كتابة محتوى المدونة',
    titleEn: 'Blog Content Writing',
    descAr: 'كتابة 3 مقالات حول فرص الاستثمار في القطاع الزراعي.',
    descEn: 'Write 3 articles about investment opportunities in the agricultural sector.',
    rewardPoints: 200,
    deadline: '2024-10-25',
    assignedTo: 'all',
    active: true,
  },
]

export const seedSubmissions: TaskSubmission[] = [
  {
    id: 'sub1',
    taskId: 'tk1',
    partnerId: 'u2',
    partnerName: 'سارة عبد الله',
    submissionUrl: 'https://example.com/campaign-results',
    submissionNote: 'تم إطلاق الحملة وحققت 12 ألف وصول.',
    status: 'pending',
    submittedAt: '2024-10-10',
  },
  {
    id: 'sub2',
    taskId: 'tk3',
    partnerId: 'u2',
    partnerName: 'سارة عبد الله',
    submissionUrl: 'https://example.com/articles',
    submissionNote: 'اكتملت المقالات الثلاثة.',
    status: 'approved',
    submittedAt: '2024-10-05',
  },
]

export const seedMessages: ChatMessage[] = [
  { id: 'm1', fromId: 'admin', fromName: 'الإدارة', fromRole: 'admin', toId: 'u2', body: 'مرحباً سارة، أداؤك ممتاز هذا الشهر!', createdAt: '2024-10-08T10:00:00', read: true },
  { id: 'm2', fromId: 'u2', fromName: 'سارة عبد الله', fromRole: 'partner', toId: 'admin', body: 'شكراً جزيلاً! متى موعد المهمة القادمة؟', createdAt: '2024-10-08T10:05:00', read: true },
  { id: 'm3', fromId: 'admin', fromName: 'الإدارة', fromRole: 'admin', toId: 'u2', body: 'ستصلك مهمة جديدة غداً صباحاً.', createdAt: '2024-10-08T10:10:00', read: false },
]

export const seedContactLinks: ContactLinks = {
  telegramPartner: 'https://t.me/arabaawy',
  telegramLanding: 'https://t.me/arabaawy',
  whatsappPartner: 'https://wa.me/201000000000',
  whatsappLanding: 'https://wa.me/201000000000',
}

export const seedPartnerRequests: PartnerRequest[] = [
  {
    id: 'pr1',
    name: 'عمر السيد',
    phone: '+201098765432',
    nationalId: '29303033456781',
    departments: ['التسويق', 'التقنية', 'المبيعات', 'الدعم'],
    portfolioUrl: 'https://example.com/omar',
    portfolioFiles: ['resume.pdf', 'projects.mp4'],
    securityQuestion: 'ما اسم أول شركة عملت بها؟',
    status: 'pending',
    code: null,
    createdAt: '2024-09-20',
  },
  {
    id: 'pr2',
    name: 'نور الدين',
    phone: '+201123459876',
    nationalId: '29609096543210',
    departments: ['المالية', 'العمليات', 'الموارد البشرية', 'الشؤون القانونية'],
    portfolioUrl: 'https://example.com/nour',
    portfolioFiles: ['cv.pdf'],
    securityQuestion: 'ما اسم مدينتك المفضلة؟',
    status: 'pending',
    code: null,
    createdAt: '2024-09-22',
  },
]
